/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kalkulator;

/**
 *
 * @author Ana
 */
public class kalk extends javax.swing.JFrame {

    /**
     * Creates new form kalk
     */
    public kalk() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtKalkulator = new javax.swing.JTextPane();
        btnIme1 = new javax.swing.JButton();
        btnIme2 = new javax.swing.JButton();
        lblRezultat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtKalkulator.setEditable(false);
        txtKalkulator.setBackground(new java.awt.Color(255, 0, 0));
        txtKalkulator.setBorder(new javax.swing.border.MatteBorder(null));
        txtKalkulator.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        txtKalkulator.setText("Ljubavni kalkulator");
        txtKalkulator.setCaretColor(new java.awt.Color(204, 0, 0));
        txtKalkulator.setDisabledTextColor(new java.awt.Color(255, 0, 204));
        txtKalkulator.setFocusable(false);
        jScrollPane1.setViewportView(txtKalkulator);

        btnIme1.setText("Unesi ime:");

        btnIme2.setText("Unesi ime simpatije:");

        lblRezultat.setText("new ciklicnaMatrica().setVisible(true);\n" +
            "		\n" +
            "		boolean dev = false;\n" +
            "		\n" +
            "		int red =dev ? 5 : Integer.parseInt(JOptionPane.showInputDialog(\"Unesi broj redova\"));\n" +
            "		int stupac =dev ? 5 : Integer.parseInt(JOptionPane.showInputDialog(\"Unesi broj stupaca\"));\n" +
            "		\n" +
            "		\n" +
            "		int[][] matrica = new int [red][stupac];\n" +
            "		\n" +
            "		\n" +
            "		int b = 1;\n" +
            "		\n" +
            "		for (int i = 1; i <= stupac; i++) {\n" +
            "			matrica[red - 1][stupac - i] = b++;\n" +
            "		}\n" +
            "				\n" +
            "		\n" +
            "		for (int i = 2; i <= red; i++) {\n" +
            "			matrica[red - i][0] = b++;\n" +
            "		}\n" +
            "		\n" +
            "\n" +
            "		for (int i = 1; i < stupac; i++) {\n" +
            "			matrica[0][i] = b++;\n" +
            "		}\n" +
            "		\n" +
            "\n" +
            "		\n" +
            "		for (int i = red - 1; i > red - (red - 1); i--) {\n" +
            "			matrica[red - i][stupac - 1] = b++;\n" +
            "		}\n" +
            "\n" +
            "		\n" +
            "		for (int i = stupac - 2; i > 0; i--) {\n" +
            "			matrica[red - 2][i] = b++;\n" +
            "		}\n" +
            "		\n" +
            "\n" +
            "		\n" +
            "		for (int i = red - 3; i > 0; i--) {\n" +
            "			matrica[i][1] = b++;\n" +
            "		}\n" +
            "\n" +
            "		for (int i = 2; i < stupac - 1; i++) {\n" +
            "			matrica[1][i] = b++;\n" +
            "		}\n" +
            "		\n" +
            "\n" +
            "		\n" +
            "		for (int i = 2; i < red - 2; i++) {\n" +
            "			matrica[i][stupac - 2] = b++;\n" +
            "		}\n" +
            "		\n" +
            "\n" +
            "		\n" +
            "		for (int i = stupac - 3; i > 1 ; i--) {\n" +
            "			matrica[red - 3][i] = b++;\n" +
            "		}\n" +
            "\n" +
            "\n" +
            "		\n" +
            "		for (int i = 0; i < red; i++) {\n" +
            "			for (int j = 0; j < stupac; j++) {\n" +
            "				System.out.print(matrica[i][j] + \"\\t\");\n" +
            "			}\n" +
            "			\n" +
            "			System.out.println();\n" +
            "			");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnIme1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(btnIme2)
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(lblRezultat, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIme1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIme2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(lblRezultat, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kalk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kalk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kalk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kalk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kalk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIme1;
    private javax.swing.JButton btnIme2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRezultat;
    private javax.swing.JTextPane txtKalkulator;
    // End of variables declaration//GEN-END:variables
}
