/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package zavrsnirad.view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import zavrsnirad.controller.ObradaBiljeska;
import zavrsnirad.controller.ObradaTermin;
import zavrsnirad.model.Biljeska;
import zavrsnirad.model.Termin;
import zavrsnirad.util.Alati;
import zavrsnirad.util.KozmetickiSalonException;

/**
 *
 * @author Ana
 */
public class ProzorBiljeska extends javax.swing.JFrame implements KozmetickiSalonViewSucelje {

    private ObradaBiljeska obrada;
    private ProzorTermin prozorTermin;
    private ObradaTermin obradaTermin;
    /**
     * Creates new form ProzorBiljeska
     */
    public ProzorBiljeska(ProzorTermin prozorTermin) {
         initComponents();
          setTitle(Alati.KOZMETICKI_SALON + " | BILJEŠKE");
          this.prozorTermin = prozorTermin;
          obradaTermin = new ObradaTermin();
          
          
          obrada = new ObradaBiljeska();
         // ucitajTermine();
          
          //lstTerminiUBazi.setModel(lstTerminiUBazi.getModel());
          //lstTerminiUBazi.repaint();
          
          ucitaj ();
  
    }

   
//private void ucitajTermine () {
        
       // private void ucitajKlijente () {
        //DefaultComboBoxModel<Klijent> m = new DefaultComboBoxModel <> ();
        //Klijent k = new Klijent ();
        //k.setSifra(0);
        //k.setIme("Odaberite");
        //k.setPrezime("klijenta");
        //m.addElement(k);
        
       // m.addAll(new ObradaKlijent().read());
        
        //cmbKlijenti.setModel(m);
        //cmbKlijenti.repaint();
        
        
        
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstBiljeske = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtOpazanje = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPreporuka = new javax.swing.JTextField();
        btnDodaj = new javax.swing.JButton();
        btnPromjena = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstTerminiUBazi = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        btnObrisiBiljesku = new javax.swing.JButton();
        btnDodajBiljesku = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lstBiljeske.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstBiljeske.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstBiljeskeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstBiljeske);

        jLabel1.setText("Bilješke");

        jLabel2.setText("Opažanje");

        jLabel3.setText("Preporuka:");

        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnPromjena.setText("Promjeni");
        btnPromjena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromjenaActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obriši");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        lstTerminiUBazi.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstTerminiUBazi.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstTerminiUBaziValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstTerminiUBazi);

        jLabel4.setText("Termini");

        btnObrisiBiljesku.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnObrisiBiljesku.setText("<<");
        btnObrisiBiljesku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiBiljeskuActionPerformed(evt);
            }
        });

        btnDodajBiljesku.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnDodajBiljesku.setText(">>");
        btnDodajBiljesku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajBiljeskuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPreporuka, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addComponent(txtOpazanje)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnDodaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnObrisi)
                            .addComponent(btnPromjena))))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnObrisiBiljesku, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDodajBiljesku, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnObrisiBiljesku, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(btnDodajBiljesku, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtOpazanje, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPreporuka, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPromjena)
                            .addComponent(btnDodaj))
                        .addGap(18, 18, 18)
                        .addComponent(btnObrisi)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed

        obrada.setEntitet(new Biljeska());
        popuniModel();
        try {
            obrada.create();
            ucitaj();
        } catch (KozmetickiSalonException ex) {
            JOptionPane.showMessageDialog(getRootPane(), ex.getPoruka());

        }
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnPromjenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromjenaActionPerformed
        if(lstBiljeske.getSelectedValue()==null){
            return;
        }

        var e = lstBiljeske.getSelectedValue();

        obrada.setEntitet(e);
        popuniModel();

        try {
            obrada.update();
            ucitaj();
        } catch (KozmetickiSalonException ex) {
            JOptionPane.showMessageDialog(getRootPane(), ex.getMessage());
            // napraviti refresh
            obrada.refresh();
        }

    }//GEN-LAST:event_btnPromjenaActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        if(lstBiljeske.getSelectedValue()==null){
            return;
        }

        var e = lstBiljeske.getSelectedValue();

        if (JOptionPane.showConfirmDialog(getRootPane(), e , "Sigurno obrisati?",
            JOptionPane.YES_NO_OPTION)!=JOptionPane.YES_OPTION){
        return;
        }

        obrada.setEntitet(e);

        try {
            obrada.delete();
            ucitaj();
        } catch (KozmetickiSalonException ex) {
            JOptionPane.showMessageDialog(getRootPane(), ex.getPoruka());
        }
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnObrisiBiljeskuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiBiljeskuActionPerformed

    if(lstBiljeske.getSelectedValue()==null){
            return;
        }
        
        DefaultListModel<Biljeska> m = (DefaultListModel<Biljeska>) lstBiljeske.getModel();
        m.removeElementAt(lstTerminiUBazi.getSelectedIndex());
        
          List<Biljeska> biljeske = new ArrayList<>();
        for (int i = 0; i < m.size(); i++) {
            biljeske.add(m.get(i));
        }

        
        
        prozorTermin.popuniView();
        lstTerminiUBazi.repaint();
        
      
        

    }//GEN-LAST:event_btnObrisiBiljeskuActionPerformed

    private void btnDodajBiljeskuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajBiljeskuActionPerformed

         if (lstBiljeske.getSelectedValue() == null) {
            return;
        }

        var b = lstBiljeske.getSelectedValue();

        boolean mozeDodati = true;
        DefaultListModel<Biljeska> m = (DefaultListModel<Biljeska>) lstBiljeske.getModel();
        List<Biljeska> biljeske = new ArrayList<>();
        for (int i = 0; i < m.size(); i++) {
            if (b.getSifra().equals(m.get(i).getSifra())) {
                mozeDodati = false;
                //break;
            }
            biljeske.add(m.get(i));
        }

        if (!mozeDodati) {
            return;
        }

        m.addElement(b);
        biljeske.add(b);
        
       
       
        
     
        
        
        
        prozorTermin.popuniView();
        lstTerminiUBazi.repaint();
        

    }//GEN-LAST:event_btnDodajBiljeskuActionPerformed

    private void lstBiljeskeValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstBiljeskeValueChanged
 if (evt.getValueIsAdjusting()) {
            return;
        }

        if (lstBiljeske.getSelectedValue() == null) {
            return;
        }

        obrada.setEntitet(lstBiljeske.getSelectedValue());

        popuniView();        // TODO add your handling code here:
    }//GEN-LAST:event_lstBiljeskeValueChanged

    private void lstTerminiUBaziValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstTerminiUBaziValueChanged
 if (evt.getValueIsAdjusting()) {
            return;
        }

        if (lstTerminiUBazi.getSelectedValue() == null) {
            return;
        }

        obradaTermin.setEntitet(lstTerminiUBazi.getSelectedValue().getKlijent());
        

        popuniView();        // TODO add your handling code here:
    }//GEN-LAST:event_lstTerminiUBaziValueChanged

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnDodajBiljesku;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnObrisiBiljesku;
    private javax.swing.JButton btnPromjena;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<Biljeska> lstBiljeske;
    private javax.swing.JList<Termin> lstTerminiUBazi;
    private javax.swing.JTextField txtOpazanje;
    private javax.swing.JTextField txtPreporuka;
    // End of variables declaration//GEN-END:variables

    @Override
    public void ucitaj() {
        DefaultListModel<Biljeska> m = new DefaultListModel<>();
        m.addAll(obrada.read());
        lstBiljeske.setModel(m);
        lstBiljeske.repaint();
    }

   @Override
    public void popuniModel() {
        var e = obrada.getEntitet();
        e.setOpazanje(txtOpazanje.getText());
        e.setPreporuka(txtPreporuka.getText());
 
    }

    @Override
    public void popuniView() {
        var e = obrada.getEntitet();
        txtOpazanje.setText(e.getOpazanje());
        txtPreporuka.setText(e.getPreporuka());
    }
}
